<script type="text/javascript" src="/public/js/jquery/jquery.form.min.js"></script>
<link rel="stylesheet" type="text/css" href="/public/js/plugins/combobox/jquery.scombobox.css">
<script src="/public/js/plugins/combobox/jquery.scombobox.js"></script>
<link href="/public/css/upload.css" rel="stylesheet" type="text/css" />

<script type="text/javascript">
$(document).ready(function() { 
	var options = { 
			target:   '#output',   // target element(s) to be updated with server response 
			beforeSubmit:  beforeSubmit,  // pre-submit callback 
			success:       afterSuccess,  // post-submit callback 
			resetForm: true        // reset the form after successful submit                      
		}; 
		
	 $('#MyUploadForm').submit(function() {                  
         
			$(this).ajaxSubmit(options);  			
			// always return false to prevent standard browser submit and page navigation 
			return false; 
		}); 
         // $('.combobox').combobox();
         $('#category').scombobox({
            //fullMatch: true
            // when fullMatch is true
            // then highligh is also true by default
        });
}); 

function afterSuccess()
{
	$('#submit-btn').show(); //hide submit button
	$('#loading-img').hide(); //hide submit button

}

//function to check file size before uploading.
function beforeSubmit(arr, $form, options){
       
    //check whether browser fully supports all File API
   if (window.File && window.FileReader && window.FileList && window.Blob)
	{
                arr.push({ 'name': 'category',
                           'value': $('.scombobox-display').val()});
               
                $('#category').val($('.scombobox-display').val());
                
		var error = '';
		if( !$('#imageInput').val()) //check empty input filed
		{
			//$("#output").html("Please select a file.");
                    error = "Please select a file.<br>";
		}
                if( !$('#category').val()) //check empty input filed
		{			
                    error = "Please select a category.<br>" + error;
		}
                if(!$('#caption').val()) //check empty input filed
		{			
		    error = "Please enter the caption field.<br>" + error;
		}
                if (error != '') {
                    $("#output").html(error);
                    return false;
                }
		
		var fsize = $('#imageInput')[0].files[0].size; //get file size
		var ftype = $('#imageInput')[0].files[0].type; // get file type
		

		//allow only valid image file types 
		switch(ftype)
        {
            case 'image/png': case 'image/gif': case 'image/jpeg': case 'image/pjpeg':
            case 'application/vnd.ms-excel': 
            case 'application/pdf': 
            case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':               
                break;
            default:
                $("#output").html("<b>"+ftype+"</b> Unsupported file type!");
				return false
        }
		
		//Allowed file size is less than 1 MB (1048576)
		/*if(fsize>1048576) 
		{
			$("#output").html("<b>"+bytesToSize(fsize) +"</b> Too big Image file! <br />Please reduce the size of your photo using an image editor.");
			return false
		}*/
				
		$('#submit-btn').hide(); //hide submit button
		$('#loading-img').show(); //hide submit button
		$("#output").html("");  
	}
	else
	{
		//Output error to older unsupported browsers that doesn't support HTML5 File API
		$("#output").html("Please upgrade your browser, because your current browser lacks some new features we need!");
		return false;
	}
}

//function to format bites bit.ly/19yoIPO
function bytesToSize(bytes) {
   var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
   if (bytes == 0) return '0 Bytes';
   var i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
   return Math.round(bytes / Math.pow(1024, i), 2) + ' ' + sizes[i];
}

</script>
<!--link href="style/style.css" rel="stylesheet" type="text/css"-->
</head>


 <div class="row">
                <div class="col-lg-12">                
        <h2 class="page-header">Business Customer File Upload</h2>
        <ol class="breadcrumb">
            <li><a href="/fm/sales-file-list">Business Customer Files</a></li>
            <li><a href="/fm/sales-file-requests">File Requests</a></li>           
            <li><a href="/fm/sales-file-request">Request a New File</a></li>
            <li class="active">Upload a File</li>
        </ol>
  </div>  
 </div>
    
<div class="row">
                <div class="col-lg-12">    
<div id="upload-wrapper">
<div align="center">
        <h3>File Upload</h3>
       
    <form method="post" enctype="multipart/form-data" id="MyUploadForm">
        <table>
            <tr><td>File:</td><td><input name="ImageFile" id="imageInput" type="file" /></td></tr><br>
            
                       
            <tr><td>Category:</td><td><select name="category" id="category"/> 
                         <option value=""></option>
                        <?foreach ($this->categories as $key => $category) :?>
                            <option value="<?= $category['name']?>"><?= $category['name']?></option>
                        <?endforeach;?></div>
                     </select>
                   
                </td>
            </tr>
       
            <tr><td>Description/Tag:</td><td><input name="caption" id="caption" type="text" /></td></tr>
        </table>
        
        <input type="submit" id="submit-btn" value="Upload" />
        <img src="/public/image/utility/ajax-loader.gif" id="loading-img" style="display:none;" alt="Please Wait"/>
    </form>
    
    <!--form class="form-horizontal" enctype="multipart/form-data" id="MyUploadForm">
         
         <div class="form-group">
               <label for="category" class="col-sm-3 control-label required">Upload</label>
                <div class="col-sm-8"> 
                <input name="ImageFile" id="imageInput" type="file"/>
                </div>
        </div>    
        
         <div class="form-group">
               <label for="category" class="col-sm-3 control-label required">Category</label>
                <div class="col-sm-8">                    
                    <select name="category"  class="combobox form-control">
                        <option value=""></option>
                        <?foreach ($this->categories as $category): ?> 
                        <option value="<?= $category['name'] ?>" <?if(isset($this->data['category']) && $this->data['category'] == $category['name']) echo 'selected';?>><?= $category['name']?></option>
                        <?endforeach;?>                        
                    </select>
                </div>
       </div>
        
       <div class="form-group">
               <label for="category" class="col-sm-3 control-label required">Tag</label>
                <div class="col-sm-8">                    
                     <input name="caption" id="caption" type="text" class="form-control" />
                </div>
       </div>   
        
        
      <input type="submit" id="submit-btn" value="Upload" />
      <img src="/public/image/utility/ajax-loader.gif" id="loading-img" style="display:none;" alt="Please Wait"/>  
     </form--> 
        
    <div id="output"></div>
    </div>
</div>
                </div>
</div>
