<div id="header">
    <div id="lonely_logo"><img src="/public/image/logo.png"></div>
<div id="lonely_logo">    
    <h2>Beaming White Business Management</h2>
</div>
</div>


<div class="container">    
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                
                    <? if (isset($this->message)): ?>   
                        <div id="login_error" class="alert alert-danger alert-dismissable">
                            <a class="close" data-dismiss="alert" href="#">×</a>
                            <?= $this->message; ?>
                        </div>
                    <? endif; ?>
                  
                <div class="login-panel panel panel-default">                  
                                       
                    
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="POST" id="loginForm">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <!--div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div-->
                                <!-- Change this to a button or input when using this as a form -->
                                <input type="submit" class="btn btn-lg btn-success btn-block" value="Log In">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</div>
<script src="/public/js/bootstrapValidator.js"></script>      
<script>
    $(document).ready(function() {   
$('#loginForm')
        .bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
               
                'email': {
                    validators: {
                         notEmpty: {
                            message: 'Email is required and cannot be empty'
                        },
                        emailAddress: {
                            message: 'The input is not a valid email address'
                        }
                    }
                },
                'password': {
                    feedbackIcons: 'false',
                    validators: {
                        notEmpty: {
                            message: 'The password is required and cannot be empty'
                        }, 
                        stringLength: {
                            min: 4,
                            max: 20,
                            message: ''
                        }
                    }
                }
            }
        });
});
</script>