<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Reset Password</h3>
    </div>
</div>
<div class="row">
    
   <div class="col-md-5">
               <? if (isset($this->message)): ?>   
                        <div id="login_error" class="alert alert-<?= $this->color?> alert-dismissable">
                            <a class="close" data-dismiss="alert" href="#">×</a>
                            <?= $this->message; ?>
                        </div>
               <? endif; ?>
       
                <div class="panel panel-default">                
                    <div class="panel-heading">
                        Reset Password
                    </div>
                    <div class="panel-body">
                        <form role="form" method="POST" id="resetForm">
                            <fieldset>
                                <label>Email</label>
                                <div class="form-group">
                                    <input class="form-control" name="email" type="email" autofocus>
                                </div>                                
                                  <label>New Password</label>
                                <div class="form-group">
                                    <input class="form-control" name="password" type="password" value="">
                                </div>
                                
                                <input type="submit" class="btn btn-lg btn-primary btn-block" value="Reset">
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
</div>
<script src="/public/js/bootstrapValidator.js"></script>      
<script>
    $(document).ready(function() {   
$('#resetForm')
        .bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
               
                'email': {
                    validators: {
                         notEmpty: {
                            message: 'Email is required and cannot be empty'
                        },
                        emailAddress: {
                            message: 'The input is not a valid email address'
                        }
                    }
                },
                'password': {
                    feedbackIcons: 'false',
                    validators: {
                        notEmpty: {
                            message: 'The password is required and cannot be empty'
                        }, 
                        stringLength: {
                            min: 4,
                            max: 20,
                            message: ''
                        }
                    }
                }
              
            }
        });
});
</script>   

