<?=$this->action('index', 'businessreport');?> 
<link rel="stylesheet" type="text/css" href="/public/css/report.css">
<div class="row">
    <!--<h3 class="page-header">Account Conversion Report</h3>    -->
    <h3 class="page-header">Account Conversion Report</h3>    
    <!-- Dariuz Rubin -->
	<div class="col-lg-12 space">
	    <form method="POST" name="verify" class="form-horizontal">
	    	<div class="row">
	    		<div class="col-md-4">
	    			<div class="form-group">
		                <label for="from" class="col-sm-3 control-label required">From:</label>   
		                <div class="col-sm-6">
		                <input name="from" class="form-control" type="text" id="from" maxlength="10" value="<?php if (isset($_POST['from'])) {
		                echo $_POST['from'];} ?>" />
		                </div>
		            </div>          
	    		</div>
	    		<div class="col-md-4">
	    			<div class="form-group">
		                <label for="to" class="col-sm-3 control-label required">To:</label>   
		                <div class="col-sm-6">
		                <input name="to" class="form-control" type="text" id="to" maxlength="10" value="<?php if (isset($_POST['to'])) {
		                echo $_POST['to'];} ?>" />
		                </div>
		            </div>       
	    		</div>
	    		<div class="col-md-4">
	    			<div class="form-group">                
		                <label for="sales" class="col-sm-3 control-label">Rep</label>
		                  <div class="col-sm-6">
		                  
		                  	<!--Dariuz Rubin-->	                  
		                  	<select id="rep" name="rep[]" multiple="multiple" class="form-control">
		                  		
		                        <? foreach ($this->reps as $rep): ?>
		                            <option value= "<?php 
		                            	echo $rep['id'].','.$rep['name']; 
		                            	?>"  <? 
		                            			$check_rep = $rep['id'].','.$rep['name'];
		                            			foreach ($_POST['rep'] as $post_rep)
		                            			{
													if ($check_rep == $post_rep)
														echo 'selected';
												}	                            		
		                            		?>><?= $rep['name'] ?></option>                          
		                        <? endforeach; ?>					       
						    </select>     				  
						    <!----------------->			    
						
		                  </div>
		            </div>  
	    		</div>
	    	</div>
	    	
	    	<div class="row">
	    		<div class="col-md-12">
	    			<center>
	    				<button type="submit" class="btn btn-default">Submit</button>
	    			</center>
	    		</div>
	    	</div>     
	    </form>    
    </div>
    <!------------------>



    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Closing Ratio Report
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
            	<div class="alert alert-info" style="margin-bottom:10px">Leads : have been assigned to or entered into the queue<br>Accounts : have been converted to accounts</div>
            	<br>
            	<div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                            	<th>Rep</th>
                                <th>Leads</th>
                                <th>Accounts</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>

                        <tbody>
                        	<?php		
						
							foreach ($this->leads_assigned as $key => $leads_assigned)
							{	
							?>
								<tr>									
									<td><?= $leads_assigned[0]['parent_user'] ?></td>
									<td><?= $leads_assigned[0]['total_leads'] ?></td>
									<td><?= $this->conversions[$key][0]['totalAccount'] ?></td>									
									<td><?php
										$percent = 0;
										if ($leads_assigned[0]['total_leads']>0) 
										{
											$percent = round($this->conversions[$key][0]['totalAccount'] / $leads_assigned[0]['total_leads'], 4) * 100;
										}
										if ($percent == 0)
											echo '';
										else
											echo $percent.'%';
										?></td>				
								</tr>
							<?php
							}				
							?>		
						
                        </tbody>
                    </table>
                </div>            
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
	<div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Specific Closing Ratio Report
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
            	<div class="alert alert-info" style="margin-bottom:10px">Leads : have been assigned to or entered into the queue<br>Accounts : have been converted to accounts from the leads which had been assigned to or entered into the queue in that same date range</div>
            	
            	<div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                            	<th>Rep</th>
                                <th>Leads</th>
                                <th>Accounts</th>
                                <th>Percentage</th>
                            </tr>
                        </thead>

                        <tbody>
                        	<?php		
							
							foreach ($this->leads_assigned as $key => $leads_assigned)
							{	
							?>
								<tr>									
									<td><?= $leads_assigned[0]['parent_user'] ?></td>
									<td><?= $leads_assigned[0]['total_leads'] ?></td>
									<td><?= $this->conversions_assigned[$key][0]['total_accounts_assigned'] ?></td>									
									<td><?php
										$percent = 0;
										if ($leads_assigned[0]['total_leads']>0) 
										{
											$percent = round($this->conversions_assigned[$key][0]['total_accounts_assigned'] / $leads_assigned[0]['total_leads'], 4) * 100;
										}
										if ($percent == 0)
											echo '';
										else
											echo $percent.'%';
										?></td>				
								</tr>
							<?php
							}				
							?>		
							
                        </tbody>
                    </table>
             	</div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>

   <div class="col-sm-6">     
        <div class="demo-info" style="margin-bottom:10px">
            <div class="demo-tip icon-tip">&nbsp;</div>            
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Accounts for Closing Ratio Report</div>
		  	<div class="panel-body">
		        <div class="alert alert-info" style="margin-bottom:10px">Accounts which have been converted to accounts in that same date range</div>
		        <table class="table table-bordered table-striped table-hover" id="account_conversion">
		            <thead>
		                <tr>
		                	<th class="header">Rep</th>
		                	<th class="header">Source</th>
		                    <th class="header">Business Name</th>
		                    <th class="header">Email</th>
		                    <th class="header">Contact Name</th>
		               
		                    <th class="header">Converted Time</th>
		                    <th class="header">Created Time</th></tr>
		            </thead>
		            <tbody>
		            	<?php							
						foreach ($this->accounts_conversions as $key => $account)
						{
							foreach ($account as $ind => $account_ind)
							{
								$link = "/crm/customer/id/".$account[$ind]['id'];
							?>
							<tr>
								<td><?= $account[$ind]['parent_user'] ?></td>
								<td><?= $account[$ind]['source'] ?></td>
		                        <td><?= $account[$ind]['businessname'] ?></td>      
		                        <td><?= $account[$ind]['email'] ?></td>      
		                        
		                        <td><?php echo "<a target='_blank' href='",$link."'>".$account[$ind]['name'].'</a>';  ?></td>
		                        <td><?= $account[$ind]['action_time'] ?></td>   
		                        <td><?= $account[$ind]['created_time'] ?></td> 
							</tr>
							<?php
							}
						}				
						?>
		            </tbody>
		        </table>
		   </div>
        </div>
 	</div>
	<div class="col-sm-6">     
        <div class="demo-info" style="margin-bottom:10px">
            <div class="demo-tip icon-tip">&nbsp;</div>            
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Accounts for Specific Closing Ratio Report</div>
		  	<div class="panel-body">
		        <div class="alert alert-info" style="margin-bottom:10px">How many of those specific leads have been converted to accounts</div>
		        <table class="table table-bordered table-striped table-hover" id="account_conversion_assigned">
		            <thead>
		                <tr>
		                	<th class="header">Rep</th>
		                	<th class="header">Source</th>
		                    <th class="header">Business Name</th>
		                    <th class="header">Email</th>
		                    <th class="header">Contact Name</th>
		                   <!-- <th class="header">Account Owner</th>-->
		                    <th class="header">Converted Time</th>
		                    <th class="header">Created Time</th></tr>
		            </thead>
		            <tbody>
		            	<?php							
						foreach ($this->accounts_conversions_assigned as $key => $account)
						{
							foreach ($account as $ind => $account_ind)
							{
								$link = "/crm/customer/id/".$account[$ind]['id'];
								
							?>
							<tr>
								<td><?= $account[$ind]['parent_user'] ?></td>
								<td><?= $account[$ind]['source'] ?></td>
		                        <td><?= $account[$ind]['businessname'] ?></td>      
		                        <td><?= $account[$ind]['email'] ?></td>      
		                        <td><?php echo "<a target='_blank' href='",$link."'>".$account[$ind]['name'].'</a>';  ?></td>
		                       
		                        <td><?= $account[$ind]['action_time'] ?></td>   
		                        <td><?= $account[$ind]['created_time'] ?></td> 
							</tr>
							<?php
							}
						}				
						?>
		            </tbody>
		        </table>
		   </div>
        </div>
 	</div>
</div>

<!-- Dariuz Rubin -->    
<link rel="stylesheet" href="/public/css/bootstrap-multiselect.css" type="text/css">
<script type="text/javascript" src="/public/js/bootstrap-multiselect.js"></script>
<!------------------>

<script src="/public/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/public/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
    $(function() {
        $("#from").datepicker({dateFormat: 'yy-mm-dd'});
        $("#to").datepicker({dateFormat: 'yy-mm-dd'});        
        $('#account_conversion').dataTable( {
              "iDisplayLength": 10       
        }); 
         $('#account_conversion_assigned').dataTable( {
              "iDisplayLength": 10       
        });  
	    
	    /* Dariuz Rubin */
	    /* Multiselect for Rep */    		
		 $('#rep').multiselect({
		   includeSelectAllOption: true,
		   buttonWidth: '100%',
		   numberDisplayed: 2	   
		});
   });
   /*=======================*/

    $(".datepicker").datepicker({
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });
    
    
</script>
