<?=$this->action('index', 'businessreport');?>          
<div class="row">
	<!-- Dariuz Rubin -->
    <h3 class="page-header">Dollar Amount</h3> 
    <!------------------>
    <div class="col-lg-12 space">
    <form method="POST" name="verify" class="form-horizontal">
    	<div class="row">
    		<div class="col-md-4">
    			<div class="form-group">
	                <label for="from" class="col-sm-3 control-label required">From:</label>   
	                <div class="col-sm-6">
	                <input name="from" class="form-control" type="text" id="from" maxlength="10" value="<?php if (isset($_POST['from'])) {
	                echo $_POST['from'];} ?>" />
	                </div>
	            </div>          
    		</div>
    		<div class="col-md-4">
    			<div class="form-group">
	                <label for="to" class="col-sm-3 control-label required">To:</label>   
	                <div class="col-sm-6">
	                <input name="to" class="form-control" type="text" id="to" maxlength="10" value="<?php if (isset($_POST['to'])) {
	                echo $_POST['to'];} ?>" />
	                </div>
	            </div>       
    		</div>
    		
    		<div class="col-md-4">
    			<div class="form-group">                
	                <label for="sales" class="col-sm-3 control-label">Rep</label>
	                  <div class="col-sm-6">
	                  
	                  	<!--Dariuz Rubin-->	                  
	                  	<select id="rep" name="rep[]" multiple="multiple" class="form-control">
	                  		
	                        <? foreach ($this->reps as $rep): ?>
	                            <option value= "<?php 
	                            	echo $rep['id'].','.$rep['name']; 
	                            	?>"  <? 
	                            			$check_rep = $rep['id'].','.$rep['name'];
	                            			foreach ($_POST['rep'] as $post_rep)
	                            			{
												if ($check_rep == $post_rep)
													echo 'selected';
											}	                            		
	                            		?>><?= $rep['name'] ?></option>                          
	                        <? endforeach; ?>					       
					    </select>     				  
					    <!----------------->			    
					
	                  </div>
	            </div>  
    		</div>
    	</div>
    	
    	<div class="row">
    		<div class="col-md-12">
    			<center>
    				<button type="submit" class="btn btn-default">Submit</button>
    			</center>
    		</div>
    	</div>     
    </form>    
    </div>
   
</div>



<div class="row">
	<? if (!empty($this->amountCustomers)): ?>
		<div class="col-lg-12">      
	        <div class="demo-info" style="margin-bottom:10px">
	            <div class="demo-tip icon-tip">&nbsp;</div>            
	        </div>
	        <div class="panel panel-default">
	            <div class="panel-heading">Customers</div>
			  	<div class="panel-body">			        
			        <table class="table table-bordered table-striped table-hover" id="dollar_amount">
			            <thead>
			                <tr>
			                	<th class="header">Rep</th>
			                 	<th class="header">Contact Name</th>
			                 	<th class="header">Sale Amount</th>
			                    <th class="header">Business Name</th>
			                    <th class="header">Enter Time</th>
			                 <!--   <th class="header">Email</th>			                    
			                    <th class="header">Created Time</th></tr>-->
			            </thead>
			            <tbody>
			            	<?php							
							foreach ($this->amountCustomers as $key => $customer)
							{
								foreach ($customer as $ind => $customer_ind)
								{
								?>
								<tr>
									<td><?= $customer[$ind]['parent_user'] ?></td>
									<td><?= $customer[$ind]['name'] ?></td>
									<td><?= $customer[$ind]['enter_sale_amount'] ?></td>      
									<td><?= $customer[$ind]['businessname'] ?></td>
									<td><?= $customer[$ind]['enter_time'] ?></td>
			                       <!-- <td><?= $customer[$ind]['email'] ?></td>      			                        
			                        <td><?= $customer[$ind]['enter_time'] ?></td> -->
								</tr>
								<?php
								}
							}				
							?>
			            </tbody>
			        </table>
			   </div>
	        </div>
	<? elseif (isset($this->isPost)) : ?>               
	        No accounts found.       
	<? endif; ?>
	 </div>
</div>

<!-- Dariuz Rubin -->    
<link rel="stylesheet" href="/public/css/bootstrap-multiselect.css" type="text/css">
<script type="text/javascript" src="/public/js/bootstrap-multiselect.js"></script>
<!------------------>
<script src="/public/js/plugins/dataTables/jquery.dataTables.js"></script>
<script src="/public/js/plugins/dataTables/dataTables.bootstrap.js"></script>
<script>
  $(function() {     	
    $("#from").datepicker({dateFormat: 'yy-mm-dd'});
    $("#to").datepicker({dateFormat: 'yy-mm-dd'});
    $('#dollar_amount').dataTable( {
              "iDisplayLength": 50       
        });   
    
    /* Dariuz Rubin */
    /* Multiselect for Rep */    
	
	 $('#rep').multiselect({
	   includeSelectAllOption: true,
	   buttonWidth: '100%',
	   numberDisplayed: 2	   
	});
   });
   /*=======================*/
</script>
