<link rel="stylesheet" type="text/css" href="/public/css/report.css">
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">CRM Reports</h1>
    </div>    
</div>
<div class="row">
	<div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                       <i class="fa fa-user-plus fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <!--div class="huge">26</div-->
                        <div>Lead Source</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/lead-source">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                       <i class="fa fa-user-plus fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <!--div class="huge">26</div-->
                        <div>Account Conversion</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/account-conversion">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-globe fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <!--div class="huge">12</div-->
                        
                        <!-- Dariuz Rubin -->
                        <div>Contact Attempts</div> 
                        <!------------------>
                    </div>
                </div>
            </div>
            <a href="/businessreport/allaccounts">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-pie-chart fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <!--div class="huge">124</div-->
                        <div>Contact Source</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/contact-source">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
   <!-- <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-2">
                        <i class="fa fa-phone fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                      
                        <div>Phone Conversion</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/phone-conversion">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>-->
    <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-compress fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <!--div class="huge">13</div-->
                        <div>Response Time</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/response-time">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
     <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-thumbs-o-up fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <!--div class="huge">13</div-->
                        <div>Follow-ups</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/follow-ups">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-bars fa-3x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div>Rep's Queues</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/rep-queues">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="report-div">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-4">
                       <i class="fa fa-money fa-3x"></i>
                    </div>
                    <div class="col-xs-8 text-right">
                        <!--div class="huge">26</div-->
                        <div>Dollar Amount</div>
                    </div>
                </div>
            </div>
            <a href="/businessreport/dollar-amount">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>    
</div>