<div class="row">
    <div class="col-lg-12">                   
        <h3 class="page-header">Internal File Sharing System - Manage Categories</h3>
        <ol class="breadcrumb">
            <li><a href="/fm/index">Shared Files</a></li>                                   
            <li><a href="/fm/upload">Upload Files</a></li>                                   
            <li class="active">Manage Categories</li>
        </ol>
    </div>

    <!-- /.col-lg-12 -->
</div>

<?if(isset($this->forbidden)):?>
<div class="alert alert-danger alert-dismissable">
    <?= $this->forbidden;?>
</div>
    <? return; ?>
<?endif;?>


<div class="row">
   
    <div class="col-lg-4">   
         <div class="panel panel-info">           
            <div class="panel-heading"> Create Category </div>
            <div class="panel-body">
        <?if (isset($this->message)):?>           
             <div class="alert alert-success alert-dismissable">
                     <a class="close" data-dismiss="alert" href="#">×</a>
                 <?= $this->message;?>                             
            </div>
        <?endif;?>
        
        <form role="form" method="POST" action="/biz/fm/category" id="categoryForm">
        <div class="form-group">
            <label>1. Select Parent Category</label>
             <select name="category_id" class="form-control">           
                <option value="0"></option>
                <? foreach ($this->categories as $category): ?>                       
                    <option value="<?= $category['category_id'] ?>"><?= $category['name'] ?></option>              
                <? endforeach; ?>
            </select>        
        </div>
        <div class="form-group">
            <label>2. Enter Category Name</label>
           <input type="text" name="name" class="form-control">
        </div>
            <input type="submit" class="btn btn-primary" value="Submit">
      </form> 
    </div>
         </div>
    </div>
    
    <div class="col-lg-1">  
    </div>
    <div class="col-lg-4">
          <?=$this->action('edit-category', 'fm');?>
    </div>
    <!-- /.col-lg-12 -->
</div>

<script src="/public/js/bootstrapValidator.js"></script>      
<script>
    $(document).ready(function() {   
$('#categoryForm')
        .bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
               
                'name': {
                    validators: {
                         notEmpty: {
                            message: 'Category name is required and cannot be empty'
                        }
                       
                    }
                }          
            }
        });
});
</script>
