<div class="row">
   
    <div class="col-lg-4">    
        
        <form role="form" method="POST" id="categoryNameForm">
        
        <div class="form-group">
            <label>Category Name</label>
           <input type="text" name="name" class="form-control" value="<?= $this->category['name']?>">
           <input type="hidden" name="category_id" value="<?= $this->category['category_id']?>">
           <input type="hidden" name="action" value="rename">
        </div>
           
      </form> 
    </div>
    <!-- /.col-lg-12 -->
</div>

<script src="/public/js/bootstrapValidator.js"></script>      
<script>
    $(document).ready(function() {   
$('#categoryNameForm')
        .bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
               
                'name': {
                    validators: {
                         notEmpty: {
                            message: 'Category name is required and cannot be empty'
                        }
                       
                    }
                }          
            }
        });
});
</script>
