<style>
    #dataTables-example tbody tr td {
        max-width:200px;  
        word-wrap: break-word;
    }
</style>
<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Internal File Sharing System</h2>
        <ol class="breadcrumb">
            <li><a href="/fm/index">File Sharing</a></li>
            <li><a href="/fm/upload">Upload Files</a></li>
            <li class="active">Shared Files</li>
        </ol>
    </div>

    <!-- /.col-lg-12 -->
</div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">                            
                            <label>Select Category:</label>                          
                            <select class="form-control" style="width: 25%" id="category" name="category">                                 
                                    <?foreach($this->categories as $category): ?>                       
                                    <option value="<?= $category['category_id']?>" <?if($category['category_id'] == $this->categoryId) echo 'selected'; ?>><?= $category['name']?> </option>                            
                                    <?endforeach;?>                                    
                            </select>                                                       
                        </div>
                        
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                              
                                 <div id="delete_error"></div>
                                
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>                                            
                                            <th>Date</th>
                                            <th>Category</th>
                                            <th>Ext</th>
                                            <th>Title</th>
                                            <th>Preview</th>
                                            <th>Description</th>
                                            <th>Size</th>
                                            <th>Uploader</th>
                                            <th>Delete</th>
                                            <th>Public</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                                                                
                                        <?foreach($this->files as $file):?>
                                            <tr class="odd gradeA" id="<?= $file['id']?>">
                                                <td><?= $file['timestamp']?></td>
                                                <td><?= $file['name']?></td>
                                                <? $ext = strrpos($file['url'], '.');
                                                   $fileExt = substr($file['url'], $ext);                                                   
                                                ?>
                                                
                                                <td><?= $fileExt?></td>
                                                <td class="center title"><a href="/fm/download/id/<?= $file['id']?>"><?= $file['title']?></a></td>
                                                <td class="center"> 
                                                    <?if(in_array($fileExt, array('.jpg', '.jpeg','.gif', '.png', '.pdf', '.mp4', '.mp3'))):?>
                                                    <button class="btn btn-primary btn-xs preview" type="button" id="<?= $file['id']?>">Preview</button>                                  
                                                    <?endif;?>
                                                </td>
                                                <td class="center"><?= $file['description'] ?></td>                                                
                                                <td class="center"><?= $file['size'] ?></td>                                      
                                                <td class="center"><?= $file['uploader']?></td>
                                                <td class="center"><button class="btn btn-danger btn-xs delete" type="button" id="<?= $file['id']?>">Delete</button></td>
                                                <td class="center"><button class="btn btn-primary btn-xs public" type="button" id="<?= $file['id']?>">Public</button></td>
                                            </tr>
                                        <?endforeach;?>
                                    </tbody>
                                </table>
                            </div>
                        
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
    <div id="dialog_public">
	<div id="public"></div>
    </div> 
            
            
  <!-- Page-Level Plugin Scripts - Tables -->
    <script src="/public/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/public/js/plugins/dataTables/dataTables.bootstrap.js"></script>
   

    <script>
       $(document).ready(function() {     
              
           $('#dataTables-example').dataTable( {
               "order": [[ 0, "desc" ]],               
           });
           
           
             $("#category").change(function() {                   
                window.location.href = '/fm/file-list/id/' + $(this).val();
             });
            $('tbody').delegate('.preview', 'click', function() { 
                   var x = screen.width/2 - 700/2;
                   var y = screen.height/2 - 450/2;
                   window.open('/fm/preview/id/' + $(this).attr("id"), "myWindowName", "directories=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no, width=700, height=450, left="+x+",top="+y);
                   return false;
              });              
           
            $('tbody').delegate('.delete', 'click', function() {  
                                                        
                var r=confirm("Delete this file? It can't be undeleted!");                
                if (r==true) {
                    $(this).closest("tr").hide();                 
                    $.post('/fm/delete', 
                    {
                        "id":$(this).attr("id")                     
                    },
                    function(data) {                           
                        if (data == 'success') {
                            $(this).closest("tr").remove();
                        } else {
                          $("#delete_error").html(data).addClass("alert alert-danger alert-dismissable");   
                        }
                    });           
                }        
        });
         $('tbody').delegate('.public', 'click', function() {  
            $('#public').html('');            
            $('#public').load('/fm/public/id/' + $(this).attr("id") );
	    $('#dialog_public').dialog('open');
         });
         
        $('#dialog_public').dialog({
		title: 'Public URL',
		autoOpen:false,
                width: 450,
		maxWidth:600,            
		modal:true,
		resizable:true,
                position:['middle',20],
		buttons: {
                    
		    Close: function() {			
			$(this).dialog('close');
                    }
		}
	});      
                 
       });
    </script>            