<div class="panel panel-info">
<div class="panel-heading"> Click to select </div>
<div class="panel-body">
    <textarea class="form-control" readonly="readonly" onclick="this.focus();this.select()">http://beamingwhite.mx/downloads/index/id/<?= $this->id?>/token/<?= $this->token?></textarea>
    
</div>
</div>

<div class="row">
     <div class="col-lg-12"> 
Send this URL to someone to download the file without registering or logging in.
     </div>
</div>    
