<style>
    #dataTables-example tbody tr td {
        max-width:200px;  
        word-wrap: break-word;
    }
</style>

<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">File Requests for Business Customers</h2>
        <ol class="breadcrumb">
            <li><a href="/fm/sales-file-list">Business Customer Files</a></li>            
            <li><a href="/fm/sales-file-request">Request a New File</a></li>
            <li><a href="/downloads/upload">Upload a File</a></li>
            <li class="active">File Requests</li>
        </ol>
    </div>

    <!-- /.col-lg-12 -->
</div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        
                        
                        <!-- /.panel-heading -->                        
                       
                        <div class="panel-body">                         
                            <div class="table-responsive">
                                                            
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>          
                                            <th>Category</th>
                                            <th>File Type</th>
                                            <th>Priority</th>
                                            <th>Status</th>
                                            <th>Description</th>
                                            <th>Requested By</th>                                            
                                            <th>Requested Time</th> 
                                            <th>Action</th> 
                                        </tr>
                                    </thead>
                                        
                                    <tbody>
                                                                               
                                        <?foreach($this->requests as $request):?>
                                            <tr class="odd gradeA" id="<?= $request['request_id']?>">                                               
                                                <td><?= $request['category']?></td>
                                                <td><?= $request['fileType']?></td>
                                                <td><?= $request['priority']?></td>
                                                <td class='status'><?= $request['status']?></td>
                                                <td><?= $request['description']?></td>
                                                <td><?= $request['requestedBy']?></td>
                                                <td><?= $request['requestedTime']?></td>   
                                                <td><button class="btn btn-primary btn-xs complete" type="button" id="<?= $request['request_id']?>">Mark as Completed</button>
                                                <button class="btn btn-danger btn-xs cancel" type="button" id="<?= $request['request_id']?>">Cancel</button></td>
                                            </tr>
                                        <?endforeach;?>
                                          
                                    </tbody>
                                    
                                </table>
                            </div>
                        
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
    <div id="dialog_public">
	<div id="public"></div>
    </div> 
            
            
  <!-- Page-Level Plugin Scripts - Tables -->
    <script src="/public/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/public/js/plugins/dataTables/dataTables.bootstrap.js"></script>
   

    <script>
       $(document).ready(function() {     
              
           $('#dataTables-example').dataTable( {
               "order": [[ 1, "desc" ]]
           });
           $('tbody').delegate('.complete', 'click', function() { 
                
                $.post('sales-file-status', 
                    {
                        "id":$(this).attr("id"),
                        "action": 'completed'
                    },
                    function(data) {                           
                        if (data == 'completed') {
                            alert('Request Marked as completed');
                            window.location.href = '/fm/sales-file-requests';
                        } 
                    });
           });
           $('tbody').delegate('.cancel', 'click', function() { 
                
                $.post('sales-file-status', 
                    {
                        "id":$(this).attr("id"),
                        "action": 'cancel'
                    },
                    function(data) {                           
                        if (data == 'canceled') {
                            alert('Request canceled');
                            window.location.href = '/fm/sales-file-requests';
                        } 
                    });
           });
                 
       });
    </script>            