<div class="row">
    <div class="col-lg-12">                   
        <h3 class="page-header">Internal File Sharing System - Upload File</h3>
        <ol class="breadcrumb">
            <li><a href="/fm/category">Manage Categories</a></li>            
            <li><a href="/fm/index">Shared Files</a></li>            
            <li class="active">Upload Files</li>
        </ol>
    </div>

    <!-- /.col-lg-12 -->
</div>


<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" type="text/css" />
<link rel="stylesheet" href="/public/js/plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css" type="text/css" />
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="/public/js/plupload/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/public/js/plupload/js/jquery.ui.plupload/jquery.ui.plupload.js"></script>
 
<?if(isset($this->forbidden)):?>
<div class="alert alert-danger alert-dismissable">
    <?= $this->forbidden;?>
</div>
    <? return; ?>
<?endif;?>


<? if (!empty($this->flashMessage)): ?>
    <div class="alert alert-success alert-dismissable">
        <? foreach ($this->flashMessage as $flash): ?>
            <a class="close" data-dismiss="alert" href="#">×</a>
            <?= $flash; ?>
        <? endforeach; ?>
    </div>
<? endif ?>

<form id="form" method="post" action="/fm/categorize">
    <input type="hidden" name="uploaded_files" id="uploaded_files" value="" />
	<div id="uploader">
		<p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
	</div>
  
	<br />
	<input type="submit" value="Submit" />
</form>

<script type="text/javascript">
$(function() {
    

	$("#uploader").plupload({
		// General settings
		runtimes : 'html5,flash,silverlight,html4',
		url : '/fm/process-upload',

		// User can upload no more then 20 files in one go (sets multiple_queues to false)
		max_file_count: 20,
		
		chunk_size: '1mb',

				
		filters : {
			// Maximum file size
			max_file_size : '2048mb'
			// Specify what files to browse for
			/*mime_types: [
				{title : "Image files", extensions : "jpg,gif,png"},
				{title : "Zip files", extensions : "zip"}
			]*/
		},                 
                
		// Rename files by clicking on their titles
		rename: true,
		
		// Sort files
		sortable: true,

		// Enable ability to drag'n'drop files onto the widget (currently only HTML5 supports that)
		dragdrop: true,

		// Views to activate
		views: {
			list: true,
			thumbs: true, // Show thumbs
			active: 'thumbs'
		},		
                flash_swf_url : '/public/js/plupload/js/Moxie.swf',
                silverlight_xap_url : '/public/js/plupload/js/Moxie.xap',
                
	});
        
      
	// Handle the case when form was submitted before uploading has finished
	$('#form').submit(function(e) {
		// Files in queue upload them first
		if ($('#uploader').plupload('getFiles').length > 0) {

			// When all files are uploaded submit form
			$('#uploader').on('complete', function() {
				$('#form')[0].submit();
			});

			$('#uploader').plupload('start');                                                                     
		} else {
			alert("You must have at least one file in the queue.");
		}
                
                              
		return false; // Keep the form from submitting
	});
});
			
</script>
