<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Item History</h2>
        <ol class="breadcrumb">          
            <li><a href="/inventory/company">Companies</a></li>
            <li><a href="/inventory/create-shipment">Create Shipment</a></li>
            <li><a href="/inventory/stock">Current Inventory</a></li>  
            <li><a href="/inventory/quantity">Inventory Adjustment</a></li>            
            <li><a href="/inventory/view">Orders</a></li>
            <li><a href="/inventory/shipments">Shipments</a></li>            
            <li class="active">Item History</li>              
        </ol>
    </div>    
</div>


<div class="col-lg-8">        
            <div class="form-group">
                <label for="item" class="col-sm-2 control-label required">Item</label>
                <div class="col-sm-8">
                    <!--input type="text" name="item" value = "" class="form-control" id="item" placeholder="Item"-->                    
                    <select name="item"  class="form-control">
                        <option value=""></option>
                        <?foreach ($this->items as $item): ?> 
                        <option value="<?= $item['itemNumber'] ?>" <?if(isset($this->itemNumber) && $this->itemNumber == $item['itemNumber'] ){echo "selected='selected'";}?>><?= $item['itemNumber'] ?> -- <?= $item['item']?></option>
                        <?endforeach;?>                        
                    </select>
                </div>
            </div>
        
</div>
<div class="col-lg-12">     
    <div id="itemResult"></div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
       $( "select[name='item']" ).change(function() {            
            $('#itemResult').html(''); 
            $("#itemResult").load("/inventory/find-item-result", {
                'id': $( this ).val()                       
            });            
        });
        <? if(isset($this->itemNumber)):?>
            $('#itemResult').html(''); 
            $("#itemResult").load("/inventory/find-item-result", {
                'id': <?= $this->itemNumber?>                     
            });           
        <? endif;?>        
    });
</script>
