<head>
     
     <style>
         #left {
             float:left;
             margin-left: 0.15em;
             width:325px;
         }
         
         table {
            border-collapse: collapse; 
         }
        
         .account {        
             margin-top: 20px;
             margin-bottom: 20px;                     
              
         }

         .account th {             
             width: 20%;
             border-top: 1px solid black;
             font-weight: bold;
             text-align: center;
         }         
        
         .account th, .account td {
             border-left: 1px solid black;
             border-bottom: 1px solid black;
             border-right: 1px solid black;
             padding: 5px;
             vertical-align:middle;             
         }
         body {
             background: transparent;             
         }
         body, td, th, input, select, textarea, option, optgroup {
             float: none !important; 
             font-family: Verdana, Arial, Helvetica, sans-serif;
             font-size: 11pt;
             color: #000000;   
             margin-left: 5%;
             margin-right: 5%;

         }
         
         
     </style>
</head>


<table width="700px">
    <tr>
        <td><?if($this->shipment['entity'] == 1):?><img src="http://beamingwhite.mx/public/image/spectrum.png"><?endif;?></td>
        <td></td><td><h1>INVOICE</h1></td><td></td>
    </tr>
    <tr><td colspan="4"></td></tr>
    <tr>
        <td><?= $this->entity['name']?></td><td></td>
        <td><b>Date:</b></td>
        <td align="left"><?= date("Y-m-d")?></td>
    </tr>
    <tr><td rowspan="2"><?= $this->entity['address']?></td><td></td>
        <td><b>Invoice #: </b></td>
        <td align="left"><?= $this->shipment['inventory_shipment_id']?></td>        
    </tr>    
    <tr><td></td><td><b>Container:</b></td><td><?= $this->shipment['container']?></td></tr>
    
    
</table>

<table width="750px" style="margin-top: 20px;">
    <tr><td colspan="3"></td></tr>
    <tr><td width="60%"><b>Bill To:</b></td><td></td><td><b>Ship To:</b></td></tr>
    <tr><td><?= $this->billTo['name']?></td><td></td><td><?= $this->shipTo['name']?></td></tr>
    <tr><td>Tax ID #: <?= $this->billTo['taxId']?>
            <br><?= $this->billTo['address']?>
            <br><?= $this->billTo['phone']?>
            <br>Attn: <?= $this->shipment['billContact']?>
        </td>
        <td></td>
        <td style="vertical-align:top;"><?= $this->shipTo['address']?>
        <br><?= $this->shipTo['phone']?>
        <br>Attn: <?= $this->shipment['shipContact']?>
        </td>        
    </tr>
    <tr><td></td></tr>
    
</table>


<table class="account" width="750px">
    <tr>
        <th>SALESPERSON</th>
        <th>CUSTOMER #</th>
        <th>CUSTOMER TAX ID</th>
        <th>SHIP VIA</th>
        <th>SHIP DATE</th>
        <th>TERMS</th>    
    </tr>
     <tr>
         <td></td>
         <td></td>
         <td></td>
         <td align="center"><?= $this->shipment['shipvia']?></td>
         <td align="center"><?= $this->shipment['shipDate']?></td>
         <td align="center"><?= $this->shipment['terms']?></td>
    </tr>   
</table>   
<table><tr><td colspan="3" rowspan="2"></td></tr></table>

<table class="account" width="750px">
    <tr>
        <th>QUANTITY</th>
        <th>Item Number</th>
        <th width="28%">DESCRIPTION</th>
        <th>UNIT PRICE</th>
        <th>AMOUNT</th>
    </tr>
    <? $subTotal = 0;?>
    <?foreach($this->shipmentItems as $shipmentItem):?>
    <tr><td align="center"><?= $shipmentItem['quantity']?></td>
        <td align="center"><?= ucwords($shipmentItem['itemNumber'])?></td>
        <td align="left" width="28%"><?= ucwords($shipmentItem['item'])?></td>
        <td align="right">US$<?= $shipmentItem['actualPrice']?></td>
        <? $rowTotal = $shipmentItem['actualPrice'] * $shipmentItem['quantity'];
           $subTotal += $rowTotal; 
        ?>
        <td align="right">US$<?=  number_format($rowTotal, 3, '.', ','); ?></td>
    </tr>
    <?endforeach;?>
    <tfoot>
        <tr><td colspan='3' style="border:none;"></td><td style="border:none;">SUBTOTAL</td><td align="right" style="border-bottom:none;">US$<?=  number_format($subTotal, 2, '.', ','); ?></td></tr>
        <tr><td colspan='3' style="border:none;"></td><td style="border:none;">TAX RATE</td><td align="right" style="border-bottom:none;"></td></tr>
        <tr><td colspan='3' style="border:none;"></td><td style="border:none;">SALES TAX</td><td align="right" style="border-bottom:none;"></td></tr>
        <tr><td colspan='2' style="border:none;"></td><td style="border:none;" colspan="2" align="right">SHIPPING & HANDLING</td><td align="right" style="border-bottom:none;"><? echo $this->shipment['freight']>0?'US$'.$this->shipment['freight']:'' ?></td></tr>
        <? $finalTotal = $subTotal + $this->shipment['freight'];?>
        <tr><td colspan='3' style="border:none;"></td><td style="border:none;"><b>TOTAL</b></td><td align="right">US$<?=  number_format($finalTotal, 2, '.', ','); ?></td></tr>
        <tr><td style="border:none; border-right: none;" colspan ="5">TOTAL: <? echo makewords($finalTotal); ?></tr>
    </tfoot>
</table>

<?

function makewords($numval){
$moneystr = "";
// handle the millions
$milval = (integer)($numval / 1000000);
if($milval > 0)  {
  $moneystr = getwords($milval) . " Million";
  }
 
// handle the thousands
$workval = $numval - ($milval * 1000000); // get rid of millions
$thouval = (integer)($workval / 1000);
if($thouval > 0)  {
  $workword = getwords($thouval);
  if ($moneystr == "")    {
    $moneystr = $workword . " Thousand";
    }else{
    $moneystr .= " " . $workword . " Thousand";
    }
  }
 
// handle all the rest of the dollars
$workval = $workval - ($thouval * 1000); // get rid of thousands
$tensval = (integer)($workval);
if ($moneystr == ""){
  if ($tensval > 0){
    $moneystr = getwords($tensval);
    }else{
    $moneystr = "Zero";
    }
  }else // non zero values in hundreds and up
  {
  $workword = getwords($tensval);
  $moneystr .= " " . $workword;
  }
 
// plural or singular 'dollar'
$workval = (integer)($numval);
if ($workval == 1){
  $moneystr .= " Dollar And ";
  }else{
  $moneystr .= " Dollars And ";
  }
 
// do the cents - use printf so that we get the
// same rounding as printf
$workstr = sprintf("%3.2f",$numval); // convert to a string

$intstr = substr($workstr,-2, 2);
$workint = (integer)($intstr);
if ($workint == 0){
  $moneystr .= "Zero";
  }else{
  $moneystr .= getwords($workint);
  }
if ($workint == 1){
  $moneystr .= " Cent";
  }else{
  $moneystr .= " Cents";
  }
 
// done 
return $moneystr;
}
 
//*************************************************************
// this function creates word phrases in the range of 1 to 999.
// pass it an integer value
//*************************************************************
function getwords($workval)
{
$numwords = array(
  1 => "One",
  2 => "Two",
  3 => "Three",
  4 => "Four",
  5 => "Five",
  6 => "Six",
  7 => "Seven",
  8 => "Eight",
  9 => "Nine",
  10 => "Ten",
  11 => "Eleven",
  12 => "Twelve",
  13 => "Thirteen",
  14 => "Fourteen",
  15 => "Fifteen",
  16 => "Sixteen",
  17 => "Seventeen",
  18 => "Eighteen",
  19 => "Nineteen",
  20 => "Twenty",
  30 => "Thirty",
  40 => "Forty",
  50 => "Fifty",
  60 => "Sixty",
  70 => "Seventy",
  80 => "Eighty",
  90 => "Ninety");
 
// handle the 100's
$retstr = "";
$hundval = (integer)($workval / 100);
if ($hundval > 0){
  $retstr = $numwords[$hundval] . " Hundred";
  }
 
// handle units and teens
$workstr = "";
$tensval = $workval - ($hundval * 100); // dump the 100's
 
// do the teens
if (($tensval < 20) && ($tensval > 0)){
  $workstr = $numwords[$tensval];
   // got to break out the units and tens
  }else{
  $tempval = ((integer)($tensval / 10)) * 10; // dump the units
  $workstr = $numwords[$tempval]; // get the tens
  $unitval = $tensval - $tempval; // get the unit value
  if ($unitval > 0){
    $workstr .= " " . $numwords[$unitval];
    }
  }
 
// join the parts together 
if ($workstr != ""){
  if ($retstr != "") {
    $retstr .= " " . $workstr;
  }
  else{
  $retstr = $workstr;
    }
  }
return $retstr;
}
 
?>