<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Inventory Adjustment</h2>
        <ol class="breadcrumb">  
            <li><a href="/inventory/company">Companies</a></li>
            <li><a href="/inventory/stock">Current Inventory</a></li>
            <li><a href="/inventory/view">Orders</a></li>
            <li><a href="/inventory/shipments">Shipments</a></li>                                 
            <li class="active">Inventory Adjustment</li>              
        </ol>
    </div>    
</div>


<div class="col-lg-8">   
         <div class="panel panel-info">           
            <div class="panel-heading">Inventory Adjustment</div>
            <div class="panel-body">
                <? if (isset($this->message)): ?>   
                        <div id="message" class="alert alert-<?= $this->color?> alert-dismissable">
                            <a class="close" data-dismiss="alert" href="#">×</a>
                            <?= $this->message; ?>
                        </div>
                    <? endif; ?>
        
        <form class="form-horizontal" id="quantityForm" method="POST">
        
            <div class="form-group">
                <label for="item" class="col-sm-2 control-label required">Item</label>
                <div class="col-sm-8">
                    <!--input type="text" name="item" value = "" class="form-control" id="item" placeholder="Item"-->                    
                    <select name="item"  class="form-control">
                        <option value=""></option>
                        <?foreach ($this->items as $item): ?> 
                        <option value="<?= $item['itemNumber'] ?>"><?= $item['itemNumber'] ?> -- <?= $item['item']?></option>
                        <?endforeach;?>                        
                    </select>
                </div>
            </div>
       
      <div class="form-group">
                <label for="quantity" class="col-sm-2 control-label required">Order ID</label>
                <div class="col-sm-8">
                    <div id="itemOrders"></div>
                </div>
       </div>
            
       <div class="form-group">
                <label for="quantity" class="col-sm-2 control-label required">Quantity</label>
                <div class="col-sm-8">
                    <input type="text" name="quantity" class="form-control" id="quantity" placeholder="Quantity">
                </div>
       </div>
            
       <div class="form-group">
                <label for="notes" class="col-sm-2 control-label required">Reason</label>
                <div class="col-sm-8">
                    <textarea  name="reason" class="form-control" rows="3"></textarea>
                </div>
        </div>    
        
            <p class="text-center"><input type="submit" class="btn btn-primary" value="Submit"></p>
           
      </form> 
    </div>
         </div>
    </div>
<script src="/public/js/bootstrapValidator.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
       $( "select[name='item']" ).change(function() {            
            $('#itemOrders').html(''); 
            $("#itemOrders").load("/inventory/ajax-item-orders", {
                'itemNumber': $( this ).val()                       
            });
        });
        $('#quantityForm')
        .bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {               
                'item': {
                    validators: {
                         notEmpty: {
                            message: 'item is required and cannot be empty'
                        }
                    }
                },
                'quantity': {
                    feedbackIcons: 'false',
                    validators: {
                        notEmpty: {
                            message: 'Quantity is required and cannot be empty'
                        }
                    }
                },
                'reason': {
                    feedbackIcons: 'false',
                    validators: {
                        notEmpty: {
                            message: 'Reason is required and cannot be empty'
                        }, 
                        stringLength: {
                            min: 4,
                            max: 1040,
                            message: ''
                        }
                    }
                }
            }
        });
        
    });
</script>
