<head>    
<link href="/public/css/plugins/dataTables/dataTables.fixedHeader.css" rel="stylesheet"> 
</head>
<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">China Inventory Shipments</h2>
        <ol class="breadcrumb">
            <li><a href="/inventory/company">Companies</a></li> 
            <li><a href="/inventory/create-order">Create Order</a></li>
            <li><a href="/inventory/stock">Current Inventory</a></li>
            <li><a href="/inventory/quantity">Inventory Adjustment</a></li>             
            <li><a href="/inventory/find-item">Item History</a></li>             
            <li><a href="/inventory/view">Orders</a></li>             
            <li><a href="/inventory/create-shipment">Create Shipment</a></li>
            <li class="active">Shipments</li>
        </ol>
    </div>    
</div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">                            
                             Inventory Shipments                                             
                        </div>
                       
                        <div class="panel-body">
                            <div class="table-responsive">
                              
                                <table class="table table-striped table-bordered table-hover table-fixed-header" cellspacing="0" width="100%" id="shipmentTable">
                                    <thead>
                                        <tr>                                            
                                            <th>Shipment Id</th>
                                            <th>Destination</th>
                                            <th>Ship Via</th>
                                            <th>Ship Date</th>   
                                            <th>Created By</th>
                                            <th>Action</th>   
                                        </tr>
                                    </thead>
                                    <tbody>
                                                                                
                                        <?foreach($this->shipments as $shipment):?>
                                            <tr class="odd gradeA">
                                                <td><?= $shipment['inventory_shipment_id']?></td>
                                                <td><?= $shipment['destination']?></td>
                                                <td><?= $shipment['shipvia']?></td>
                                                <td><?= $shipment['shipDate']?></td>
                                                <td><?= $shipment['created_by']?></td>
                                                <td class="center">
                                                    <a href="/inventory/update-shipment/id/<?= $shipment['inventory_shipment_id']?>" class="btn btn-primary btn-xs">View/Update</a>                                                    
                                            </tr>
                                        <?endforeach;?>
                                    </tbody>
                                </table>
                            </div>
                        
                        </div>
                       
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
            
  <!-- Page-Level Plugin Scripts - Tables -->
    <script src="/public/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/public/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <!--script src="/public/js/plugins/dataTables/dataTables.fixedHeader.min.js"></script-->
    <script src="/public/js/plugins/dataTables/dataTables.fixedHeader.js"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {   
        //var table =  $('#shipmentTable').dataTable( {  
        $('#shipmentTable').dataTable( {             
            "aoColumns": [     
      null,
      null,
      null,
      null,
      null,     
      { "bSortable": false }      
      ],
     "order": [[ 3, "desc" ]],
      "iDisplayLength": 100,
     "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]]
     
} );
    //new $.fn.dataTable.FixedHeader( table );
    
    
    var fixedHeaders = [];
$('.table-fixed-header').each(function () {
    fixedHeaders.push(
        new FixedHeader(this, {
            'offsetTop': 51 // offset for my bootstrap .navbar-fixed-top
        })
    );
});
 
$(window).resize(function () {
    for (var i = 0; i < fixedHeaders.length; i++) {
        fixedHeaders[i]._fnUpdateClones(true); // force redraw
        fixedHeaders[i]._fnUpdatePositions();
    }
});
   
    });
    </script>