<head>
    <link rel="stylesheet" type="text/css" href="/public/css/crm.css">	 
</head> 
<div style="margin-bottom: 5px;"><h2>Shipments</h2></div>    
        <table class="account" border="0" cellspacing="0" cellpadding="0">
            <thead>
               <tr>
                <th>Transaction Time</th>                 
                <th>Who</th>                
                <th>Notes</th>
                <th>Quantity</th> 
               </tr>
           </thead>
           <tbody>               
               <? $total = 0;?>
                 <? foreach($this->transactions as $transaction):?>    
                       <tr>
                       <td align="left"><?= $transaction['transaction_time'] ?></td>                        
                       <td align="left"><?= $transaction['author']?></td> 
                       <td align="left"><?= $transaction['notes']?></td>                       
                       <td align="right"><?= $transaction['quantity']?></td>  
                       <? $total += $transaction['quantity'];?>
                       </tr>
                 <? endforeach; ?>
           </tbody>
           <tfoot>
               <tr><td colspan="2"></td><td>QOH</td><td align="right"><?= $total?></td></tr>
           </tfoot>
        </table>
