<?
    $id = $this->user['id'];
    $link_param = "/id/".$id;

    
?>

<head>    
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/css/jqueryui-editable.css" rel="stylesheet"/>
    <link href="/public/css/jquery.datetimepicker.css" rel="stylesheet" />
	<script src="/public/js/jquery/jquery.datetimepicker.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/js/jqueryui-editable.min.js"></script> 
    <script src="/public/js/jquery/jquery-editable-poshytip.js"></script>       	
</head>


<div class="row" name="branch_div" id="branch_div">
	
		<div class="row">
			<div class="col-sm-offset-1 col-sm-10 customer-detail-col">
				<table class="table my-table-font" cellspacing="0" cellpadding="0">	
					 <tbody>					 	
					     <tr>
					        <td class = "customer-detail-left-field customer-detail-font">Branch Name</td>
					        <td>	
					        	<select class="customer-detail-field customer-detail-black-font" name="branch_name" id="branch_name">
					        		<? foreach ($this->branches as $key => $branch ): ?>
					                    <option value= "<?= $branch['branch_name']?>"  <? if ($this->branch['branch_name'] == $branch['branch_name']) echo 'selected';?>><?= $branch['branch_name']?></option>
					                <? endforeach; ?>				    
								</select>     
					        </td>		
					        <td align="right">					    	
			                	<button type="button"  class="btn btn-primary  customer-detail-button customer-detail-font <?php if ($this->user['type'] == 'Account') echo 'account-panel-heading'; else if ($this->user['type'] == 'Prospect') echo 'prospect-panel-heading'; else if ($this->user['type'] == 'Lead') echo 'lead-panel-heading'; ?>"  id="submitNewBranch" name="submitNewBranch"  style="width:120px" onclick="javascript:ClickNewButton('<?= $link_param?>')" >New </button>			                	
					        </td>			
					    </tr>					  
					 </tbody>
				</table>				
			</div>
		</div>
		<br />
		<div class="row">
			<div class="col-sm-offset-1 col-sm-10 customer-detail-col">
				<div class="panel panel-primary customer-detail-panel">
					<div class="panel-heading customer-detail-font customer-detail-section-head-font <?php if ($this->user['type'] == 'Account') echo 'account-panel-heading'; else if ($this->user['type'] == 'Prospect') echo 'prospect-panel-heading'; else if ($this->user['type'] == 'Lead') echo 'lead-panel-heading'; ?>">Contact & Company Information</div>
					<div class="panel-body <?php if ($this->user['type'] == 'Account') echo 'account-panel'; else if ($this->user['type'] == 'Prospect') echo 'prospect-panel'; else if ($this->user['type'] == 'Lead') echo 'lead-panel';?>">
						<table class="table my-table-font" cellspacing="0" cellpadding="0">				
							 <tbody>					 	
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Business Name</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="businessname" id="businessname" value="<?php 
							        		if (isset($this->branch['businessname']) and strlen($this->branch['businessname'])>0) 
							        			echo $this->branch['businessname'];
							        		else
							        			echo $this->branch['firstname'].' '.$this->branch['lastname'];?>"/>
							        </td>					        
							    </tr>
								<tr>
							        <td class = "customer-detail-left-field customer-detail-font">Business Type</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="businesstype" id="businesstype" value="<?= $this->branch['businesstype']?>"/>
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">First Name</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="firstname" id="firstname" value="<?= $this->branch['firstname']?>"/>
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Last Name</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="lastname" id="lastname" value="<?= $this->branch['lastname']?>"/>
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Phone</td>
							        <td>		
							        	<?php
							        		if (isset($this->branch['contactphone_all']))
							        			$contactphones_ary = explode(',',$this->branch['contactphone_all']);
							        		for ($i=0;$i<5;$i++)
							        		{
							        			$id = "contact_phone_". $i;
											?>
											<div class="row"  id = '<?= $id?>' style="<?php 
												if (!isset($contactphones_ary[$i]) and $i) 
													echo 'display:none';
												?>">
									        	<div>
									        		<input class="customer-detail-field customer-detail-font customer-detail-added" name="contactphones[]" type="text" value="<?php if (isset($contactphones_ary[$i])) echo trim($contactphones_ary[$i]);?>"/>	
											    </div>
											 							
				                            </div>
											<?php	
											}
							        	?>
			                                                    
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Email</td>
							        <td>		
							        	<?php
							        		if (isset($this->branch['email_all']))
							        			$email_ary = explode(',',$this->branch['email_all']);
							        		for ($i=0;$i<5;$i++)
							        		{
							        			$id = "contact_email_". $i;
											?>
											<div class="row"  id = '<?= $id?>' style="<?php 
												if (!isset($email_ary[$i]) and $i)  
													echo 'display:none';
												?>">
									        	<div>
									        		<input class="customer-detail-field customer-detail-font customer-detail-added" name="contactemails[]" type="text" value="<?php if (isset($email_ary[$i])) echo trim($email_ary[$i]);?>"/>	
											    </div>
											 
							                   								
				                            </div>
											<?php	
											}
							        	?>						        	 
			                                        
							        </td>					        
							    </tr>					  
							       
							 </tbody>
						</table>
						<table class="table my-table-font" cellspacing="0" cellpadding="0"  id="secondaryContactTable">				
							 <tbody>		
							 	<tr style="margin-bottom: 20px">
							        <td class = "customer-detail-left-field customer-detail-font" colspan="2" align="center" style="color:black;font-size:19px">Secondary Contact & Company Information</td>					        
							    </tr>			 	
							   	<tr style="height:15px">&nbsp;</tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Business Name</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="secondary_businessname" id="secondary_businessname" value="<?= $this->branch['secondary_businessname']?>"/>
							        </td>					        
							    </tr>
								<tr>
							        <td class = "customer-detail-left-field customer-detail-font">Business Type</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="secondary_businesstype" id="secondary_businesstype" value="<?= $this->branch['secondary_businesstype']?>"/>
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">First Name</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="secondary_firstname" id="secondary_firstname" value="<?= $this->branch['secondary_firstname']?>"/>
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Last Name</td>
							        <td>					        						        	
							        	<input  type="text" class="customer-detail-field customer-detail-font" name="secondary_lastname" id="secondary_lastname" value="<?= $this->branch['secondary_lastname']?>"/>
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Phone</td>
							        <td>		
							        	<?php
							        		if (isset($this->branch['contactphone2_all']))
							        			$contactphones2_ary = explode(',',$this->branch['contactphone2_all']);
							        		for ($i=0;$i<5;$i++)
							        		{
							        			$id = "secondary_contact_phone_". $i;
											?>
											<div class="row"  id = '<?= $id?>' style="<?php 
												if (!isset($contactphones2_ary[$i]) and $i)  
													echo 'display:none';
												?>">
									        	<div>
									        		<input class="customer-detail-field customer-detail-font customer-detail-added" name="secondary_contactphones[]" type="text" value="<?php if (isset($contactphones2_ary[$i])) echo trim($contactphones2_ary[$i]);?>"/>	
											    </div>
											 							
				                            </div>
											<?php	
											}
							        	?>						        	
							        </td>					        
							    </tr>
							    <tr>
							        <td class = "customer-detail-left-field customer-detail-font">Email</td>
							        <td>
							        	<?php
							        		if (isset($this->branch['email2_all']))
							        			$email2_ary = explode(',',$this->branch['email2_all']);
							        		for ($i=0;$i<5;$i++)
							        		{
							        			$id = "secondary_contact_email_". $i;
											?>
											<div class="row"  id = '<?= $id?>' style="<?php 
												if (!isset($email2_ary[$i]) and $i)  
													echo 'display:none';
												?>">
									        	<div>
									        		<input class="customer-detail-field customer-detail-font customer-detail-added" name="secondary_contactemails[]" type="text" value="<?php if (isset($email2_ary[$i])) echo trim($email2_ary[$i]);?>"/>	
											    </div>
											 				
				                            </div>
											<?php	
											}
							        	?>						      		
							        	
			                                        
							        </td>					        
							    </tr>
							 </tbody>
						</table>				
					</div>
				</div>			
			</div>		
		</div>
		
	
	
</div>

<script type="text/javascript">    	
	function ClickNewButton(link)
	{
		
		var url = "/crm/create-branch"+link;
		window.open(url);
	}
</script>
<script>
	$(document).ready(function() {   
	   $(function() {
	        $("#tabs").tabs(							
	        {
	            beforeLoad: function(event, ui) 
	            {
	                ui.jqXHR.error(function() {
	                    ui.panel.html(
	                            "Please Wait...");
	                });
	            }
	        });
		    $("#tabs").tabs().css(			
		        {
	            'min-height': '400px',
	            'overflow': 'auto'
	        });   
	        $("#branch_name").change(function(){
	        	var branch_name = $(this).val();
	        	
	        	
	        	var data = {"id": <?= $this->user['id']?>,
            		"branch_name":branch_name};    	            		
            		
		     	$.ajax({
		            type: "POST",
		            url: "/biz/crm/branch-info",
		            data: data,
		            dataType: 'html',
		            success: function(data) {
		            	
						console.log(data);
						
						window.location.reload();
						
						/*$("#branch_div").load(location.href+" #branch_div>*","");*/
		            }
		        });
        
        
			});
	     
	    });    
	    
	});
</script>
<!--<style type="text/css">
	.customer-detail-font{
		font-size: 14px !important;
		font-family :Verdana, Arial, Helvetica, sans-serif;	    
	    font-style: italic !important;
	}
	.customer-detail-black-font{
		font-size: 14px !important;
		font-family :Verdana, Arial, Helvetica, sans-serif;	    
	    font-style: italic !important;
	    color: black;
	}
	 
	.customer-detail-section-head-font{
		font-size: 18px !important;
		text-align: center;
	}
	.customer-detail-field{
		width: 100%;
	    border: 2px solid #c4c4c4;
	    border-radius: 3px;
	    
	}
	.customer-detail-date-field{
		width: 40%;
	    
	}
	.customer-detail-image-field{
		background-image: url(/public/image/calendar.png);
	  	background-position: 5px 50%;
	  	background-repeat: no-repeat;	 	
	 	padding-left: 35px;
	 	width: 100%;
	 	color: black;
	}
	.customer-detail-left-field{
		width: 40%;
	    color: #737373;
	    vertical-align: middle !important;
	}
	.customer-detail-left-activity-field{
		width: 65%;
	    color: #737373;
	    vertical-align: middle !important;
	}
	.customer-detail-button{
		/*    width: 100%;
	    height: 112%;
	    padding-top: 5px;
	    padding-bottom: 0px;*/
	    border-radius: 0px;
	    width: 100%;
	}
	table, tr, td {
	    border: none !important;
	   	    
	}
	table{
		margin-bottom: auto !important;
	}
	.customer-detail-panel{
		margin-bottom: 20px;
	}
	.panel-body {
		border-width:2px;
		border-color: #428bca;
		padding-top: 10px;
    	padding-bottom: 10px;
    	background-color: #f2f0f1;
	}
	.account-panel-heading {
	    color: #fff !important;
	    background-color: #428bca !important;
	    border-color: #428bca !important;
	}
	.lead-panel-heading {
	    color: #fff !important;
	    background-color: green !important;
	    border-color: green !important;
	}
	.prospect-panel-heading {
	    color: #4c4646 !important;
	    /*background-color: aqua !important;
	     border-color:aqua !important;*/
	    background-color: rgb(21,202,204) !important;
	    border-color:rgb(21,202,204) !important;
	   
	}
	.account-panel {		
		border-color: #428bca;		
	}
	.lead-panel {		
		border-color: green;		
	}
	.prospect-panel {		
		/*border-color: aqua;*/
		 border-color:rgb(21,202,204) !important;
	}
	.row{
		margin-left: auto;
		margin-right: auto;
	}	
	.customer-detail-col{
		/*padding:3px;*/
	}
	.customer-detail-followup-left-field{
		width: 80%;
	    color: #737373;
	    vertical-align: middle;
	}
	.entry:not(:first-of-type)
	{
	    margin-top: 10px;
	}

	.glyphicon
	{
	    font-size: 18px;
	}
	.input-group-addon, .input-group-btn {
	    vertical-align: top;
	}
	.table>tbody>tr>td{
		padding-top: 4px !important;
    	padding-bottom: 4px !IMPORTANT;
	}
	.customer-detail-added{
		margin-bottom: 4px;		
	}
	.customer-detail-activity-checkbox{
		    /* font-size: 210%; */
	    -ms-transform: scale(2);
	    -moz-transform: scale(2);
	    -webkit-transform: scale(2);
	    -o-transform: scale(2);	
	    margin-top: 13px !important;	
	    
	}
	    
</style>-->
