<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Sales CRM - Create <?= $this->type?></h2>
        <ol class="breadcrumb">                                             
            <li><a href="/crm/leads">Leads</a></li>             
            <li><a href="/crm/prospect">Prospect</a></li>  
            <li><a href="/crm/leads">Accounts</a></li> 
            <li><a href="/crm/activity">Activities</a></li>
            
            <li class="dropdown" style='margin-left: 60%;'>
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    Create <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li> <a href="/crm/create-user/type/lead">Lead</a></li>
                    <li> <a href="/crm/create-user/type/Prospect">Prospect</a></li>
                    <li> <a href="/crm/create-user/type/Account">Account</a></li>
                </ul>                
           </li>
        </ol>
    </div>    
</div>

<div class="row">
  <div style="float:right;">    
      <?=$this->action('search', 'crm');?>
  </div>      
  
  <div class="col-lg-12">
    <? echo $this->form;?>
  </div>
</div> 


<script>    
$(document).ready(function() {
	$("#submit").hide();
	$("#submit_type").val("Normal");
	$("#submit_type").hide();
    $("#country").change(function() {
            $.ajax({
                url: '/crm/ajax-get-regions',
                dataType: 'html',
                type: "POST",
                data: {country: $(this).val()},
                success: function(data) {
                    $('#state').html(data);
                }
            });

        });
     /* Dariuz Rubin */
	 $("#submit_check").click(function() {
	 	var address1 = $('#address1').val();
	 	var address2 = $('#address2').val();
	 	var firstname = $('#firstname').val();
	 	var lastname = $('#lastname').val();
	 	var contactphone = $('#contactphone').val();
	 	var contactphone2 = $('#contactphone2').val();
	 	var email = $('#email').val();
	 	var email2 = $('#email2').val();
	 	$.ajax({
            url: '/crm/search-account',
            dataType: 'html',
            type: "POST",
            data: 'address1=' + address1 + '&address2=' + address2 + '&firstname=' + firstname + '&lastname=' + lastname + '&contactphone=' + contactphone + '&email=' + email+ '&contactphone2=' + contactphone2+ '&email2=' + email2,
            success: function(res){
            	console.log(res);
                if (res == 'Yes')
                {
					if (confirm('This contact already exists in system! \nDo you still want to create the new account?\nIf you click Cancel, we will have the rep of the current one notified that you talked to the existing rep\'s customer.')) 
			 		{
			 			$("#submit_type").val("Create");
			 			$("#submit").click();				        
				    }else
				    {
				    	$("#submit_type").val("Noitfy");
						$("#submit").click();
					}
				}else
				{
					$("#submit").click();	
				}
            }
        });
     });
	 /*====================*/
 });
</script>