<head>  
    <script>
        $(function() {
        	
        	/* Dariuz Rubin */
   			$(".saveButton").click(function() {
                    
                
				formData = $("#customer_info_form").serialize();
	                        //alert (formData);
				$.ajax({                                    
					type: "POST",
					url: "/crm/save-account-info",
					data: formData,
					dataType: 'html',
					success: function(data) 
					{
	                	location.reload();
	                }
				});
            });
            /*================*/
            
            $("#tabs").tabs({
                beforeLoad: function(event, ui) {
                    ui.jqXHR.error(function() {
                        ui.panel.html(
                                "Waiting...");
                    }
                    );
                }
            });
     <?if (in_array('delete_crm', unserialize(Zend_Auth::getInstance()->getIdentity()->permission))):?>
                $(".deleteButton").click(function() {
                    var r = confirm("Are you sure you want to delete this account?");
                    if (r == true) {
                        $.post('/crm/delete-customer',
                                {
                                    "id": $(this).attr("id")
                                },
                        function(data) {
                            if (data == 'success') {
                                window.location.href = '/crm/leads'
                            } else {
                                $("#delete_error").html(data).addClass("error");
                            }
                        });
                    }
                });

         <? endif; ?>
        });
    </script>
</head>

<div class="row">
      <div class="col-lg-12 page-header" style="padding: 0px;padding-top: 10px;margin-bottom: 10px">            
            <div class="col-lg-6">
                <h2 style="margin: 0px">Sales CRM - Customer Detail</h2>
            </div>
            <div style="margin-top: 0px;">
                <?=$this->action('search', 'crm');?> 
            </div>
         </div>
   <!-- <div class="col-lg-12">                           
        <ol class="breadcrumb">                            
            <li><a href="/crm/leads">Leads</a></li>             
            <li><a href="/crm/prospect">Prospects</a></li>             
            <li><a href="/crm/accounts">Accounts</a></li>  
            <li><a href="/crm/activity">Activities</a></li>           
        </ol>
    </div>    -->
</div>
<!-- Dariuz Rubin -->
<div class="row" style="margin-bottom: 5px">
	<div class="col-sm-8 col-xs-8">
		<span class="crm-title"><?= $this->type ?> <?= $this->customerName; ?>&nbsp;</span>
		<?if (in_array('delete_crm', unserialize(Zend_Auth::getInstance()->getIdentity()->permission))):?>
		    <span class="btn btn-danger btn-xs deleteButton" id="<?= $this->customerId; ?>">Delete</span>
		<? endif; ?>
		<span class="btn btn-success btn-md saveButton" id="<?= $this->customerId; ?>">Save</span>
	</div>
	<div class="col-sm-4 col-xs-4" align="right">
		<a class="spacing" href="/crm/customer/prev/<?= $this->customerId; ?>/type/<?= $this->type ?>"><b>Previous</b></a>  
   		<a href="/crm/customer/next/<?= $this->customerId; ?>/type/<?= $this->type ?>"><b>Next</b></a>
	</div>
</div>
<!--<span class="crm-title"><?= $this->type ?> <?= $this->customerName; ?>&nbsp;</span>
<?if (in_array('delete_crm', unserialize(Zend_Auth::getInstance()->getIdentity()->permission))):?>
    <span class="btn btn-danger btn-xs deleteButton" id="<?= $this->customerId; ?>">Delete</span>
<? endif; ?>
<span class="btn btn-success btn-xs saveButton" id="<?= $this->customerId; ?>">Save</span>
<div id="delete_error"></div>
<div id="right">
    <a class="spacing" href="/crm/customer/prev/<?= $this->customerId; ?>/type/<?= $this->type ?>"><b>Previous</b></a>  
    <a href="/crm/customer/next/<?= $this->customerId; ?>/type/<?= $this->type ?>"><b>Next</b></a>
</div>-->
<!------------------->

<div id="tabs" class="easyui-tabs crm-customer-detail"> 
    <ul>
        <li><a href="/crm/view/id/<?= $this->customerId; ?>">Account</a></li>
        <li><a href="/crm/branch-info/id/<?= $this->customerId; ?>">Branch Info</a></li>
        <li><a href="/crm/documents/id/<?= $this->customerId; ?>">Documents</a></li>
        
        <!--<li><a href="/crm/address-book/id/<?= $this->customerId; ?>">Address Book</a></li>
        <li><a href="/crm/payment/id/<?= $this->customerId; ?>">Payment Cards</a></li>
        <li><a href="/crm/order-history/id/<?= $this->customerId; ?>">Order History</a></li>-->
        <li><a href="/crm/product/id/<?= $this->customerId; ?>">Product</a></li>       
        <li><a href="/crm/price/id/<?= $this->customerId; ?>">Pricing</a></li>       
        <li><a href="/crm/transaction/id/<?= $this->customerId; ?>">Transaction</a></li>
        <li><a href="/crm/activity/id/<?= $this->customerId; ?>">Activity</a></li>
    </ul>
</div>


<style type="text/css">
	#page-wrapper{
		border:none;
		
	}
	.customer-detail-font{
		font-size: 12px !important;
		font-family :Verdana, Arial, Helvetica, sans-serif;	    
	    font-style: italic !important;
	}
	.customer-detail-black-font{
		font-size: 12px !important;
		font-family :Verdana, Arial, Helvetica, sans-serif;	    
	    font-style: italic !important;
	    color: black;
	}
	 
	.customer-detail-section-head-font{
		font-size: 16px !important;
		text-align: center;
	}
	.customer-detail-field{
		width: 100%;
	    border: 2px solid #c4c4c4;
	    border-radius: 3px;
	    
	}
	.customer-detail-date-field{
		width: 40%;
	    
	}
	.customer-detail-image-field{
		background-image: url(/public/image/calendar.png);
	  	background-position: 5px 50%;
	  	background-repeat: no-repeat;	 	
	 	padding-left: 35px;
	 	width: 100%;
	 	color: black;
	}
	.customer-detail-left-field{
		width: 40%;
	    color: #737373;
	    vertical-align: middle !important;
	}
	.customer-detail-left-activity-field{
		width: 65%;
	    color: #737373;
	    vertical-align: middle !important;
	}
	.customer-detail-button{
		/*    width: 100%;
	    height: 112%;
	    padding-top: 5px;
	    padding-bottom: 0px;*/
	    border-radius: 0px;
	    width: 100%;
	}
	.table>tbody>tr>td {
	    padding-top: 2px !important;
	    padding-bottom: 2px !IMPORTANT;
	}
	table, tr, td {
	    border: none !important;
	   	    
	}
	table{
		margin-bottom: auto !important;
	}
	.btn-add{
		padding-left: 2px;
	    padding-right: 2px;
	    padding-top: 5px;
	    padding-bottom: 5px;
	}
	.customer-detail-panel{
		margin-bottom: 5px;
	}
	.panel-body {
		border-width:2px;
		border-color: #428bca;
		padding-top: 10px;
    	padding-bottom: 10px;
    	background-color: #f2f0f1;
	}
	.account-panel-heading {
	    color: #fff !important;
	    background-color: #428bca !important;
	    border-color: #428bca !important;
	}
	.lead-panel-heading {
	    color: #fff !important;
	    background-color: green !important;
	    border-color: green !important;
	}
	.prospect-panel-heading {
	    color: #4c4646 !important;
	    /*background-color: aqua !important;
	     border-color:aqua !important;*/
	    background-color: rgb(21,202,204) !important;
	    border-color:rgb(21,202,204) !important;
	   
	}
	.account-panel {		
		border-color: #428bca;		
	}
	.lead-panel {		
		border-color: green;		
	}
	.prospect-panel {		
		/*border-color: aqua;*/
		 border-color:rgb(21,202,204) !important;
	}
	.row{
		margin-left: auto;
		margin-right: auto;
	}	
	.customer-detail-col{
		padding:10px;
	}
	.customer-detail-followup-left-field{
		width: 80%;
	    color: #737373;
	    vertical-align: middle;
	}
	.entry:not(:first-of-type)
	{
	    margin-top: 10px;
	}

	.glyphicon
	{
	    font-size: 16px;
	}
	.input-group-addon, .input-group-btn {
	    vertical-align: top;
	}
	
	.customer-detail-added{
		margin-bottom: 4px;		
	}
		.customer-detail-activity-checkbox{
		    /* font-size: 210%; */
	    -ms-transform: scale(1.2);
	    -moz-transform: scale(1.2);
	    -webkit-transform: scale(1.2);
	    -o-transform: scale(1.2);	
	    margin-top: 13px !important;	
	    
	}
	    
</style>