<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Sales CRM</h2>
        <ol class="breadcrumb">               
            <li><a href="/crm/prospect">Leads</a></li> 
            <li><a href="/crm/prospect">Prospects</a></li>             
            <li><a href="/crm/accounts">Accounts</a></li> 
            <li><a href="/crm/activity">Activities</a></li>
			<li class="active">Tradeshows</li>
        </ol>
    </div>    
</div>

<h3>Tradeshows</h3>

<?php 
$servername = "localhost";
$username = "bwbiz";
$password = "BWbiz2014";
$dbname = "bwerp";

// Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);
$choice = addslashes($_GET['choice']);

// Check connection
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}
// echo "Connected successfully";
echo "<br />";

// Select from database
$sql = "SELECT DISTINCT city, state, country FROM tradeshows ORDER BY tradeshows . id ASC";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
	echo '<h2>City, State, and Country</h2>';
	echo '<select id="ts">';
    while($row = $result->fetch_assoc()) {
        echo "<option value=" . $row["id"] . ">" . $row["city"] . ", " . $row["state"] . ", " . $row["country"] . "</option>";
    }
	echo '</select>';
} else {
    echo "0 results";
}
$conn->close();

?>

<script>

	$("#ts").change(function() {
		alert("there was a change");
	});

/*	$(function() {
		$("#tradeshow").change(function() {
			$("#showname").load("/public/textdata/tradeshow/" + $(this).val() + ".txt");
		});
		$("#showname").change(function() {
			$("#tscity").load("/public/textdata/tradeshow/name/" + $(this).val() + ".txt");
		});
		$("#tscity").change(function() {
			$("#tsyear").load("/public/textdata/tradeshow/name/city/" + $(this).val() + ".txt");
		});
		$("#tsyear").change(function() {
			alert("year");
		});
	});
*/
	
</script>
<link href='/public/css/crm.css' rel='stylesheet' />

