
<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Sales CRM</h2>
        <ol class="breadcrumb">                                 
            <li><a href="/crm/leads">Leads</a></li>
            <li><a href="/crm/prospect">Prospects</a></li>             
            <li><a href="/crm/accounts">Accounts</a></li> 
            <li><a href="/crm/activity">Activities</a></li>            
        </ol>
    </div>    
</div>

<div class="row">
    <div class="col-lg-8">    
        <div class="panel panel-info">           
                <div class="panel-heading">Internal Order Creation Form</div>
                <div class="panel-body">
                <form class="form-horizontal" method="POST" action="order-info">

                        <div class="form-group">
                                <label for="quantity" class="col-sm-2 control-label required">Email</label>
                                <div class="col-sm-8">
                                    <input type="text" size="56" id="email" name="email" placeholder="Primary Email">
                                </div>
                       </div>
                            <p class="text-center"><input type="submit" class="btn btn-primary" value="Submit"></p>
                </form>
                </div>
        </div>
    </div>
</div>    