<div class="row">
    <div class="col-lg-12">                   
        <h2 class="page-header">Sales CRM</h2>
        <ol class="breadcrumb">                                 
            <li><a href="/crm/leads">Leads</a></li>
            <li><a href="/crm/prospect">Prospects</a></li>             
            <li><a href="/crm/accounts">Accounts</a></li> 
            <li><a href="/crm/activity">Activities</a></li>            
        </ol>
    </div>    
</div>

<div class="row">
    <div class="col-lg-12">
Thank you for your order
    </div>
</div>    